# Zero — The Collapse of Infinity

**Consolidated ZERO-only simulations**

**Destiny Machwaya** · **Copyright © 2015–2026 Destiny Machwaya. All rights reserved.**

The following computational experiments are restricted to finite folded-zero arithmetic, inverse-pair closure, boundary growth, symbolic projection/return and the corresponding visualizations. Numerical/visual constructions are not redefinitions of zero.

## Finite folded-zero simulations and scaling

In [114]:
!pip -q install numpy pandas plotly ipywidgets

In [115]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

from IPython.display import display
import ipywidgets as widgets

In [116]:
def folded_zero(N):
    """
    Finite QTET folded-zero construction:

        0_N = 0 + Σ[n + (-n)], n = 1...N

    Every lawful inverse pair closes to zero.
    """

    if N < 1:
        raise ValueError("N must be >= 1")

    positive = np.arange(1, N + 1)
    negative = -positive

    pair_sum = positive + negative

    total = pair_sum.sum()

    return {
        "N": N,
        "positive": positive,
        "negative": negative,
        "pair_sum": pair_sum,
        "total": total
    }

In [117]:
for N in [1, 10, 100, 1_000, 100_000]:
    result = folded_zero(N)

    print(
        f"N = {N:>7,}   "
        f"pairs = {len(result['pair_sum']):>7,}   "
        f"result = {result['total']}"
    )

N =       1   pairs =       1   result = 0
N =      10   pairs =      10   result = 0
N =     100   pairs =     100   result = 0
N =   1,000   pairs =   1,000   result = 0
N = 100,000   pairs = 100,000   result = 0

In [118]:
def plot_number_line(N=10):

    states = np.arange(-N, N + 1)

    fig = go.Figure()

    fig.add_trace(
        go.Scatter(
            x=states,
            y=np.zeros_like(states),
            mode="markers+text",
            text=states,
            textposition="top center",
            marker=dict(size=10),
            name="Lawful numerical states"
        )
    )

    fig.add_trace(
        go.Scatter(
            x=[0],
            y=[0],
            mode="markers",
            marker=dict(size=20, symbol="diamond"),
            name="0 reference"
        )
    )

    fig.update_layout(
        title=f"Sequential Number-Line Representation | N = {N}",
        xaxis_title="Numerical state",
        yaxis_visible=False,
        height=350
    )

    fig.show()

In [119]:
plot_number_line(10)

In [121]:
def folded_coordinates(N):
    """
    Visualization coordinates only.

    +n and -n remain distinct lawful numerical states,
    while their inverse-pair relationship is made geometrically visible.
    """

    n = np.arange(1, N + 1)

    # Spread pairs around a circle
    theta = 2 * np.pi * (n - 1) / N

    # Radius grows with |n|
    radius = n / N

    # +n branch
    x_pos = radius * np.cos(theta)
    y_pos = radius * np.sin(theta)

    # -n branch mirrored through the origin
    x_neg = -x_pos
    y_neg = -y_pos

    return {
        "n": n,
        "theta": theta,
        "radius": radius,
        "x_pos": x_pos,
        "y_pos": y_pos,
        "x_neg": x_neg,
        "y_neg": y_neg
    }

In [122]:
def plot_folded_zero(N=12):

    coords = folded_coordinates(N)

    fig = go.Figure()

    # Draw inverse-pair relationships
    for i, n in enumerate(coords["n"]):

        fig.add_trace(
            go.Scatter(
                x=[
                    coords["x_pos"][i],
                    0,
                    coords["x_neg"][i]
                ],
                y=[
                    coords["y_pos"][i],
                    0,
                    coords["y_neg"][i]
                ],
                mode="lines",
                line=dict(width=1),
                showlegend=False,
                hoverinfo="skip"
            )
        )

    # Positive states
    fig.add_trace(
        go.Scatter(
            x=coords["x_pos"],
            y=coords["y_pos"],
            mode="markers+text",
            text=[f"+{n}" for n in coords["n"]],
            textposition="top center",
            marker=dict(size=10),
            name="+n"
        )
    )

    # Negative states
    fig.add_trace(
        go.Scatter(
            x=coords["x_neg"],
            y=coords["y_neg"],
            mode="markers+text",
            text=[f"-{n}" for n in coords["n"]],
            textposition="bottom center",
            marker=dict(size=10),
            name="-n"
        )
    )

    # Folded total-state reference
    fig.add_trace(
        go.Scatter(
            x=[0],
            y=[0],
            mode="markers+text",
            text=["0"],
            textposition="middle center",
            marker=dict(
                size=28,
                symbol="circle"
            ),
            name="0 — folded total-state reference"
        )
    )

    fig.update_layout(
        title=f"Folded Inverse-Pair Representation | N = {N}",
        xaxis=dict(
            visible=False,
            scaleanchor="y",
            scaleratio=1
        ),
        yaxis=dict(
            visible=False
        ),
        height=650,
        showlegend=True
    )

    fig.show()

In [123]:
plot_folded_zero(12)

In [124]:
def simultaneous_state_string(N=5):

    negative = list(range(-N, 0))
    positive = list(range(1, N + 1))

    states = negative + [0] + positive

    state_text = ", ".join(str(x) for x in states)

    return "{ " + state_text + " }^||"

In [125]:
print(simultaneous_state_string(5))

{ -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5 }^||

In [126]:
def pair_closure_table(N=10):

    n = np.arange(1, N + 1)

    df = pd.DataFrame({
        "n": n,
        "+n": n,
        "-n": -n,
        "pair closure": n + (-n)
    })

    return df

In [127]:
display(pair_closure_table(10))

    n  +n  -n  pair closure
0   1   1  -1             0
1   2   2  -2             0
2   3   3  -3             0
3   4   4  -4             0
4   5   5  -5             0
5   6   6  -6             0
6   7   7  -7             0
7   8   8  -8             0
8   9   9  -9             0
9  10  10 -10             0

In [128]:
def boundary_growth(max_power=6):

    N_values = np.array([
        10**p for p in range(max_power + 1)
    ])

    state_counts = 2 * N_values + 1

    closure_values = []

    for N in N_values:

        n = np.arange(1, N + 1, dtype=np.int64)

        closure = np.sum(n + (-n))

        closure_values.append(closure)

    return pd.DataFrame({
        "N": N_values,
        "represented_states": state_counts,
        "closure": closure_values
    })

In [129]:
growth = boundary_growth(6)

display(growth)

         N  represented_states  closure
0        1                   3        0
1       10                  21        0
2      100                 201        0
3     1000                2001        0
4    10000               20001        0
5   100000              200001        0
6  1000000             2000001        0

In [130]:
def plot_boundary_growth(df):

    fig = go.Figure()

    fig.add_trace(
        go.Scatter(
            x=df["N"],
            y=df["represented_states"],
            mode="lines+markers",
            name="Represented lawful states"
        )
    )

    fig.add_trace(
        go.Scatter(
            x=df["N"],
            y=df["closure"],
            mode="lines+markers",
            name="Pair closure"
        )
    )

    fig.update_layout(
        title="Increasing Boundary vs. Finite Closure",
        xaxis=dict(
            title="Boundary N",
            type="log"
        ),
        yaxis_title="Value",
        height=500
    )

    fig.show()

In [131]:
plot_boundary_growth(growth)

In [132]:
N_slider = widgets.IntSlider(
    value=8,
    min=1,
    max=40,
    step=1,
    description="Boundary N:",
    continuous_update=False
)

display(
    widgets.interactive(
        plot_folded_zero,
        N=N_slider
    )
)

interactive(children=(IntSlider(value=8, continuous_update=False, description='Boundary N:', max=40, min=1), O…

In [133]:
def project_state(n, N):

    if abs(n) > N:
        raise ValueError(
            f"State {n} lies outside the selected finite boundary ±{N}."
        )

    return n

In [134]:
N = 20

for target in [-12, -3, 0, 7, 18]:
    print(
        f"π_{target}(0_Q) →",
        project_state(target, N)
    )

π_-12(0_Q) → -12
π_-3(0_Q) → -3
π_0(0_Q) → 0
π_7(0_Q) → 7
π_18(0_Q) → 18

In [135]:
class FoldedTotalState:
    def __repr__(self):
        return "0_Q"


ZERO_Q = FoldedTotalState()


def rho(n):
    return ZERO_Q

In [136]:
for n in [-100, -2, 0, 4, 91]:

    projected = n
    returned = rho(projected)

    print(
        f"π_{n}(0_Q) = {projected:>4}   "
        f"ρ({projected}) = {returned}"
    )

π_-100(0_Q) = -100   ρ(-100) = 0_Q
π_-2(0_Q) =   -2   ρ(-2) = 0_Q
π_0(0_Q) =    0   ρ(0) = 0_Q
π_4(0_Q) =    4   ρ(4) = 0_Q
π_91(0_Q) =   91   ρ(91) = 0_Q

In [138]:
def animate_projection_return(n=7, frames=50):

    magnitude = abs(n)

    if magnitude == 0:
        magnitude = 1

    # Outward projection
    outward = np.linspace(0, magnitude, frames)

    # Return
    inward = np.linspace(magnitude, 0, frames)

    path = np.concatenate([outward, inward])

    direction = 1 if n >= 0 else -1

    x_path = direction * path

    fig = go.Figure(
        data=[
            go.Scatter(
                x=[x_path[0]],
                y=[0],
                mode="markers",
                marker=dict(size=22)
            )
        ],
        layout=go.Layout(
            title=f"π_{n}(0_Q) → n → ρ(n) → 0_Q",
            xaxis=dict(
                range=[-magnitude - 1, magnitude + 1],
                title="Differentiated state"
            ),
            yaxis=dict(
                range=[-1, 1],
                visible=False
            ),
            height=350,
            updatemenus=[
                dict(
                    type="buttons",
                    buttons=[
                        dict(
                            label="Play",
                            method="animate",
                            args=[
                                None,
                                {
                                    "frame": {
                                        "duration": 35,
                                        "redraw": True
                                    },
                                    "fromcurrent": True
                                }
                            ]
                        )
                    ]
                )
            ]
        ),
        frames=[
            go.Frame(
                data=[
                    go.Scatter(
                        x=[x],
                        y=[0],
                        mode="markers",
                        marker=dict(size=22)
                    )
                ]
            )
            for x in x_path
        ]
    )

    fig.show()

In [139]:
animate_projection_return(-8)

In [140]:
def zero_scaling_experiment(
    boundaries=(10, 100, 1_000, 10_000, 100_000, 1_000_000)
):

    records = []

    for N in boundaries:

        n = np.arange(
            1,
            N + 1,
            dtype=np.int64
        )

        closure = np.sum(n + (-n))

        records.append({
            "boundary_N": N,
            "positive_states": N,
            "negative_states": N,
            "total_represented_states": 2 * N + 1,
            "pair_closure": closure,
            "closure_preserved": closure == 0
        })

    return pd.DataFrame(records)

In [141]:
zero_results = zero_scaling_experiment()

display(zero_results)

,boundary_N,positive_states,negative_states,total_represented_states,pair_closure,closure_preserved
0,10,10,10,21,0,True
1,100,100,100,201,0,True
2,1000,1000,1000,2001,0,True
3,10000,10000,10000,20001,0,True
4,100000,100000,100000,200001,0,True
5,1000000,1000000,1000000,2000001,0,True

In [143]:
zero_results.to_csv(
    "QTET_inside_zero_scaling_results.csv",
    index=False
)

print("Saved: QTET_inside_zero_scaling_results.csv")

Saved: QTET_inside_zero_scaling_results.csv

## Independent folded-zero mathematics lab

## Module 1 — Folded Zero Mathematics

Finite inverse-pair closure, symbolic projection/return, and folded-state visualization.

**Interpretation rule:** canonical QTET/QTL-Sphere objects are preserved where explicitly identified. Any encoding, embedding, distance, spectrum, deformation, matrix transform, graph lift, or score introduced here is an **analysis / visualization construction**, not a replacement definition of the underlying framework.

In [3]:
RNG = np.random.default_rng(42)  # Reset for deterministic module-local experiments.

### 1. Canonical zero forms used in this notebook

The notebook preserves the disclosed finite form

\[
0_N = 0 + \sum_{n=1}^{N}(n+(-n)) = 0,
\]

and the folded/simultaneous notation

\[
0_Q = \{\ldots,-3,-2,-1,0,1,2,3,\ldots\}^{\parallel}.
\]

The symbol \(\parallel\) denotes simultaneous lawful coexistence in the disclosed formulation. The code below does **not** identify this notation with an ordinary convergent infinite series; it tests finite inverse-pair closure and symbolic projection/return relationships.

In [4]:
def folded_zero_finite(N):
    N = int(N)
    if N < 0:
        raise ValueError('N must be >= 0')
    n = np.arange(1, N + 1, dtype=np.int64)
    pair_sums = n + (-n)
    return {
        'N': N,
        'represented_states': 2 * N + 1,
        'pair_count': N,
        'closure': int(pair_sums.sum()) if len(pair_sums) else 0,
        'all_pairs_close': bool(np.all(pair_sums == 0)),
    }

rows = [folded_zero_finite(N) for N in [0,1,2,10,100,1000,100000,1000000]]
zero_growth = pd.DataFrame(rows)
display(zero_growth)

         N  represented_states  pair_count  closure  all_pairs_close
0        0                   1           0        0             True
1        1                   3           1        0             True
2        2                   5           2        0             True
3       10                  21          10        0             True
4      100                 201         100        0             True
5     1000                2001        1000        0             True
6   100000              200001      100000        0             True
7  1000000             2000001     1000000        0             True

### 2. Inverse-pair closure as the boundary expands

The state count grows as \(2N+1\), while every explicitly represented inverse pair still closes to ordinary scalar zero. This separates **size of the represented finite state set** from **pair-sum closure**.

In [5]:
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=zero_growth['N'].replace(0, np.nan),
    y=zero_growth['represented_states'],
    mode='lines+markers',
    name='Represented finite states'
))
fig.add_trace(go.Scatter(
    x=zero_growth['N'].replace(0, np.nan),
    y=zero_growth['closure'],
    mode='lines+markers',
    name='Pair-sum closure'
))
fig.update_layout(
    title='Finite boundary growth vs inverse-pair closure',
    xaxis_type='log',
    xaxis_title='Finite boundary N (log scale)',
    yaxis_title='Value',
    height=500
)
fig.show()

### 3. Symbolic projection and return

The disclosed relationships are represented symbolically:

\[
\pi_n(0_Q)=n,
\qquad
\rho(n)=0_Q,
\qquad
\rho(\pi_n(0_Q))=0_Q.
\]

`0_Q` is intentionally represented as a symbolic object rather than Python's scalar integer `0`.

In [6]:
class FoldedTotalState:
    def __repr__(self):
        return '0_Q'

ZERO_Q = FoldedTotalState()

def pi_n(n):
    return int(n)

def rho(_n):
    return ZERO_Q

projection_examples = []
for n in [-100, -7, -1, 0, 1, 7, 100]:
    projected = pi_n(n)
    projection_examples.append({
        'n': n,
        'pi_n(0_Q)': projected,
        'rho(pi_n(0_Q))': repr(rho(projected))
    })
display(pd.DataFrame(projection_examples))

     n  pi_n(0_Q) rho(pi_n(0_Q))
0 -100       -100            0_Q
1   -7         -7            0_Q
2   -1         -1            0_Q
3    0          0            0_Q
4    1          1            0_Q
5    7          7            0_Q
6  100        100            0_Q

### 4. Folded inverse-pair visualization

This geometry is only a visualization. Opposite signed integers are placed as paired points connected through a central reference.

In [7]:
def folded_geometry(N=12):
    N = int(N)
    n = np.arange(1, N+1)
    theta = 2*np.pi*(n-1)/max(N,1)
    r = n/max(N,1)
    xp, yp = r*np.cos(theta), r*np.sin(theta)
    xn, yn = -xp, -yp
    fig = go.Figure()
    for i in range(N):
        fig.add_trace(go.Scatter(
            x=[xp[i],0,xn[i]], y=[yp[i],0,yn[i]],
            mode='lines', line=dict(width=1),
            showlegend=False, hoverinfo='skip'
        ))
    fig.add_trace(go.Scatter(x=xp,y=yp,mode='markers+text',text=[f'+{v}' for v in n],name='+n'))
    fig.add_trace(go.Scatter(x=xn,y=yn,mode='markers+text',text=[f'-{v}' for v in n],name='-n'))
    fig.add_trace(go.Scatter(x=[0],y=[0],mode='markers+text',text=['0_Q ref'],marker=dict(size=22),name='folded reference'))
    fig.update_layout(title=f'Folded inverse-pair visualization | N={N}',xaxis=dict(visible=False,scaleanchor='y'),yaxis=dict(visible=False),height=650)
    fig.show()

folded_geometry(12)

### 5. Foundation check

Within the finite numerical construction tested here, inverse-pair closure is exact for every tested boundary. This is a computational check of the finite identity; it is not a numerical proof of the full interpretive content assigned to \(0_Q\).